Repository alexlafroscia/ember-runtime-config, pull requests merged in 2022-04, with the labels that each got.

#2 chore: drop Node.js <= 12 support
  package.json
Labels: breaking

#3 chore: bump lint dependencies
  .eslintrc.js
  .gitignore
  .prettierignore
  .prettierrc.js
  blueprints/ember-runtime-config/index.js
  commitlint.config.js
  config/ember-try.js
  config/environment.js
  ember-cli-build.js
  index.js
  lib/get-config.js
  middleware/index.js
  package.json
  testem.js
  tests/acceptance/smoke-test-test.js
  tests/dummy/app/app.js
  tests/dummy/app/controllers/application.js
  tests/dummy/app/resolver.js
  tests/dummy/app/router.js
  tests/dummy/config/ember-runtime-config.js
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  yarn.lock
Labels: internal

#4 chore: add `eslint-plugin-qunit` per latest addon blueprint
  .eslintrc.js
  package.json
  yarn.lock
Labels: internal

#5 chore: run `ember-cli-update` to sync with latest addon blueprint
  .editorconfig
  .ember-cli
  .eslintignore
  .github/workflows/ci.yml
  .gitignore
  .husky/commit-msg
  .npmignore
  .template-lintrc.js
  .travis.yml
  CONTRIBUTING.md
  README.md
  addon/.gitkeep
  config/ember-try.js
  ember-cli-build.js
  index.js
  package.json
  testem.js
  tests/dummy/app/controllers/.gitkeep
  tests/dummy/app/index.html
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/components/.gitkeep
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/environment.js
  tests/dummy/config/optional-features.json
  tests/dummy/config/targets.js
  tests/helpers/.gitkeep
  tests/helpers/index.js
  tests/index.html
  tests/test-helper.js
  yarn.lock
Labels: internal

#6 feat: add `runtime-config` template helper
  README.md
  addon/helpers/runtime-config.js
  app/helpers/runtime-config.js
  package.json
  tests/integration/.gitkeep
  tests/integration/helpers/runtime-config-test.js
  yarn.lock
Labels: enhancement

#7 feat(middleware): add no-store to Cache-Control header
  middleware/index.js
Labels: enhancement

#9 feat(fastboot): allow fastboot specific config
  README.md
  fastboot/index.js
  tests/dummy/config/fastboot-testing.js
  tests/fastboot/fastboot-test.js
  yarn.lock
Labels: enhancement

#8 feat: add test helper
  README.md
  addon-test-support/helpers/set-runtime-config.js
  addon-test-support/index.js
  tests/acceptance/smoke-test-test.js
Labels: enhancement
